apiVersion: v1
kind: Pod
metadata:
  name: greeter-client-lookaside-lb
spec:
  containers:
  - name: greeter-client-lookaside-lb
    image: gcr.io/grpc-loadbalancing-demo2018/greeter_client_lookaside_lb:latest
    env:
    - name: GRPC_VERBOSITY
      value: "debug"
    # grpclb can only be used with "ares" DNS resolvers
    - name: GRPC_DNS_RESOLVER
      value: "ares"
    # Enable for extra detailed traces
    #- name: GRPC_TRACE
    #  value: "glb,client_channel"
  restartPolicy: Never
