apiVersion: v1
kind: Service
metadata:
  name: greeter-server
spec:
  # Make this a headless service so that each endpoint will be exposed
  # as a separate DNS A record.
  clusterIP: None
  ports:
  - port: 8000
  selector:
    app: grpclb-demo
    tier: backend
